apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-vs-grpc
spec:
  hosts:
    {{- range .Values.gateway.hosts }}
    - {{ . | quote }}
    {{- end }}
  gateways:
    - {{ .Release.Name }}-gateway-grpc
  http:
    {{- range .Values.gateway.features }}
    - match:
        - headers:
            host:
              exact: {{ . }}
      route:
        - destination:
            host: app-srv-prod-il-jerusalem-1.app-srv.svc.cluster.local
            subset: canary
            port:
              number: {{ $.Values.appServicePort }}
    {{- end }}
    - route:
        - destination:
            host: app-srv-prod-il-jerusalem-1.app-srv.svc.cluster.local
            subset: stable
            port:
              number: {{ .Values.appServicePort }}
