apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ .Release.Name }}-srv1-dr
spec:
  host: app-srv-prod-il-jerusalem-1.app-srv.svc.cluster.local
  subsets:
    - name: canary
      labels:
        version: canary
    - name: stable
      labels:
        version: stable
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-vs
spec:
  hosts:
    {{- range .Values.virtualService.hosts }}
    - {{ . | quote }}
    {{- end }}
  gateways:
    - {{ .Release.Name }}-gateway
  http:
    - match:
        - headers:
            host:
              exact: canary.einav.com
      route:
        - destination:
            host: app-srv-prod-il-jerusalem-1.app-srv.svc.cluster.local
            subset: canary
            port:
              number: {{ .Values.appServicePort }}
    # - route:
    #     - destination:
    #         host: app-srv-prod-il-jerusalem-1.app-srv.svc.cluster.local
    #         subset: stable
    #         port:
    #           number: {{ .Values.appServicePort }}
