apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-private-vs
spec:
  hosts:
    {{- range (index .Values "gateway-private").hosts }}
    - {{ . | quote }}
    {{- end }}
  gateways:
    - {{ .Release.Name }}-gateway-private
  http:
    - match:
        - headers:
            host:
              exact: kiali.einav.com
      route:
        - destination:
            host: kiali.istio-system.svc.cluster.local
            port:
              number: 20001
    