apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-vs
spec:
  hosts:
    {{- range .Values.virtualService.hosts }}
    - {{ . | quote }}
    {{- end }}
  gateways:
    - {{ .Release.Name }}-gateway
  http:
    - match:
        - uri:
            prefix: /srv1
      rewrite:
        uri: /
      route:
        - destination:
            host: app-srv-prod-il-jerusalem-1.app-srv.svc.cluster.local
            port:
              number: {{ .Values.appServicePort }}
    - match:
        - uri:
            prefix: /srv2
      rewrite:
        uri: /
      route:
        - destination:
            host: app-srv2-prod-il-jerusalem-1.app-srv2.svc.cluster.local
            port:
              number: {{ .Values.appServicePort }}

