apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: product-helm-apps
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  argocd.argoproj.io/secret-type: cluster
          - git:
              repoURL: https://github.com/einavle/oci-infra.git
              revision: HEAD
              files:
                - path: product/helm/*/config.json
  template:
    metadata:
      name: '{{.path.basename}}-{{ index .metadata.labels "env" }}-{{ index .metadata.labels "region" }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/einavle/oci-infra.git
        targetRevision: '{{ default "HEAD" .targetRevision }}'
        path: "{{.path.path}}"
        helm:
          valueFiles:
            - '{{ index .metadata.labels "env" }}/{{ index .metadata.labels "region" }}/values.yaml'
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{.path.basename}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
