appServiceName: app-srv
appServicePort: 80

gateway:
  hosts:
    - "app1.einav.com"

gatewayGrpc:
  hosts:
    - "app2.einav.com"

virtualService:
  hosts:
    - "app1.einav.com"

htmlServerVirtualService:
  enabled: true
  host: html-server.html-server.svc.cluster.local
  port: 80
  timeout: 1s
  faultDelay: 0s
  faultPercentage: 0
