apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Release.Name }}-gateway-grpc
spec:
  selector:
    istio: ingress-grpc
  servers:
    - port:
        number: 80
        name: http-grpc
        protocol: HTTP
      hosts:
        {{- range .Values.gatewayGrpc.hosts }}
        - {{ . | quote }}
        {{- end }}
