{{- if .Values.srvServerVirtualService.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-html-server-vs
spec:
  hosts:
    - {{ .Values.srvServerVirtualService.host | quote }}
  http:
    - timeout: {{ .Values.srvServerVirtualService.timeout }}
      route:
        {{- if .Values.srvServerVirtualService.canary.enabled }}
        - destination:
            host: {{ .Values.srvServerVirtualService.host | quote }}
            subset: stable
            port:
              number: {{ .Values.srvServerVirtualService.port }}
          weight: {{ sub 100 .Values.srvServerVirtualService.canary.weight }}
        - destination:
            host: {{ .Values.srvServerVirtualService.host | quote }}
            subset: canary
            port:
              number: {{ .Values.srvServerVirtualService.port }}
          weight: {{ .Values.srvServerVirtualService.canary.weight }}
        {{- else }}
        - destination:
            host: {{ .Values.srvServerVirtualService.host | quote }}
            port:
              number: {{ .Values.srvServerVirtualService.port }}
        {{- end }}
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ .Release.Name }}-html-server-dr
spec:
  host: {{ .Values.srvServerVirtualService.host | quote }}
  subsets:
    - name: stable
      labels:
        version: {{ .Values.srvServerVirtualService.canary.stableVersion }}
    - name: canary
      labels:
        version: {{ .Values.srvServerVirtualService.canary.canaryVersion }}
{{- end }}
