apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-vs-grpc
spec:
  hosts:
    {{- range .Values.gatewayGrpc.hosts }}
    - {{ . | quote }}
    {{- end }}
  gateways:
    - {{ .Release.Name }}-gateway-grpc
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: app-srv.app-srv.svc.cluster.local
            port:
              number: {{ .Values.appServicePort }}
