appServiceName: app-srv
appServicePort: 80

gateway:
  hosts:
    - "argocd.israel-takeaway.com"
    - "*.israel-takeaway.com"
    - "sensor.einav.com"
    - "israel-takeaway.com"
    - "srv1.israel-takeaway.com"
    - "feature1.einav.com"
    - "feature2.einav.com"

  features:
    - "feature1.einav.com"
    - "feature2.einav.com"
    # - "srv1.israel-takeaway.com"

gateway-private:
  hosts:
    - "kiali.einav.com"






htmlServerVirtualService:
  enabled: true
  host: app-srv-prod-il-jerusalem-1.happ-srv.svc.cluster.local
  port: 80
  timeout: 1s
  faultDelay: 0s
  faultPercentage: 0
  stableVersion: stable
  canaryVersion: canary
  canary:
    enabled: false
    weight: 20
